export const UKRAINE_REGIONAL_CENTERS = [
  { value: '__all__', label: 'Вся Україна' },
  { value: 'kyiv', label: 'Київ' },
  { value: 'vinnitsa', label: 'Вінниця' },
  { value: 'dnipro', label: 'Дніпро' },
  { value: 'donetsk', label: 'Донецьк' },
  { value: 'zhitomir', label: 'Житомир' },
  { value: 'zaporizhzhia', label: 'Запоріжжя' },
  { value: 'ivano-frankivsk', label: 'Івано-Франківськ' },
  { value: 'kropyvnytskyi', label: 'Кропивницький' },
  { value: 'lugansk', label: 'Луганськ' },
  { value: 'lutsk', label: 'Луцьк' },
  { value: 'lviv', label: 'Львів' },
  { value: 'mykolaiv', label: 'Миколаїв' },
  { value: 'odesa', label: 'Одеса' },
  { value: 'poltava', label: 'Полтава' },
  { value: 'rivne', label: 'Рівне' },
  { value: 'sumy', label: 'Суми' },
  { value: 'ternopil', label: 'Тернопіль' },
  { value: 'uzhhorod', label: 'Ужгород' },
  { value: 'kharkiv', label: 'Харків' },
  { value: 'kherson', label: 'Херсон' },
  { value: 'khmelnytskyi', label: 'Хмельницький' },
  { value: 'cherkasy', label: 'Черкаси' },
  { value: 'chernivtsi', label: 'Чернівці' },
  { value: 'chernihiv', label: 'Чернігів' },
  { value: 'simferopol', label: 'Сімферополь' },
];

export const UKRAINE_REGIONAL_CENTERS_WITHOUT_ALL = [
  { value: 'kyiv', label: 'Київ' },
  { value: 'vinnitsa', label: 'Вінниця' },
  { value: 'dnipro', label: 'Дніпро' },
  { value: 'donetsk', label: 'Донецьк' },
  { value: 'zhitomir', label: 'Житомир' },
  { value: 'zaporizhzhia', label: 'Запоріжжя' },
  { value: 'ivano-frankivsk', label: 'Івано-Франківськ' },
  { value: 'kropyvnytskyi', label: 'Кропивницький' },
  { value: 'lugansk', label: 'Луганськ' },
  { value: 'lutsk', label: 'Луцьк' },
  { value: 'lviv', label: 'Львів' },
  { value: 'mykolaiv', label: 'Миколаїв' },
  { value: 'odesa', label: 'Одеса' },
  { value: 'poltava', label: 'Полтава' },
  { value: 'rivne', label: 'Рівне' },
  { value: 'sumy', label: 'Суми' },
  { value: 'ternopil', label: 'Тернопіль' },
  { value: 'uzhhorod', label: 'Ужгород' },
  { value: 'kharkiv', label: 'Харків' },
  { value: 'kherson', label: 'Херсон' },
  { value: 'khmelnytskyi', label: 'Хмельницький' },
  { value: 'cherkasy', label: 'Черкаси' },
  { value: 'chernivtsi', label: 'Чернівці' },
  { value: 'chernihiv', label: 'Чернігів' },
  { value: 'simferopol', label: 'Сімферополь' },
];
export const KYIV_DISTRICTS = [
  'Голосіївський',
  'Дарницький',
  'Деснянський',
  'Дніпровський',
  'Оболонський',
  'Печерський',
  'Подільський',
  'Святошинський',
  "Солом'янський",
  'Шевченківський',
] as const;
