import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { dehydrate, QueryClient } from "@tanstack/react-query";
import { queryKeys } from "@/lib/reactQuery/queryKeys";

import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import { ThemeProvider } from "@/providers/theme-provider";
import ClientProvider from "@/providers/UserProvider";
import { getAllBusinessCategories } from "@/lib/actions/businessCategories";
import { getAllSpecialOffers } from "@/lib/actions/specialOffers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const supabase = await createClient();
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery({
    queryKey: queryKeys.businessCategories,
    queryFn: getAllBusinessCategories,
  });

  // Prefetch global special offers
  await queryClient.prefetchQuery({
    queryKey: queryKeys.specialOffers,
    queryFn: getAllSpecialOffers,
  });
  const dehydratedState = dehydrate(queryClient);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider dehydratedState={dehydratedState}>
            {children}
            <ClientProvider />
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
