import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from "@tanstack/react-query";
import { queryKeys } from "@/lib/reactQuery/queryKeys";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import { ThemeProvider } from "@/providers/theme-provider";
import ClientProvider from "@/providers/UserProvider";
import { getAllBusinessCategories } from "@/lib/actions/businessCategories";
import { getBusinesses } from "@/lib/actions/businesses";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const supabase = await createClient();
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery({
    queryKey: queryKeys.businessCategories,
    queryFn: getAllBusinessCategories,
  });
  const dehydratedState = dehydrate(queryClient);
  // await queryClient.prefetchQuery({
  //   queryKey: [
  //     "businesses",
  //     { city: "__all__", categoryId: "__all__", sortBy: "newest" },
  //   ],
  //   queryFn: () =>
  //     getBusinesses({
  //       city: "__all__",
  //       categoryId: "__all__",
  //       sortBy: "newest",
  //     }),
  // });
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider dehydratedState={dehydratedState}>
            {/* <HydrationBoundary state={dehydratedState}> */}
            {children}
            <ClientProvider />
            {/* </HydrationBoundary> */}

            <ReactQueryDevtools initialIsOpen={false} />
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
